### ISSUE TITLE
laravel plugin (v. 0.7.2) get me full namespace path to controller

### ISSUE THREAD

**Issue by mrden** [Haehnchen/idea-php-laravel-plugin#31]
See the attached image.
![original](https://cloud.githubusercontent.com/assets/331554/6878620/106f8910-d503-11e4-9808-769c5fefb730.jpg)

**Comment by sonnyvan** [comment]
I have the same issue as well with this version.

**Comment by spetz83** [comment]
I am also having this issue.

**Comment by bgeree** [comment]
same here

**Comment by visualight** [comment]
Same problem for me

**Comment by T-Spoon** [comment]
Likewise here

**Comment by usagi-yojimbo** [comment]
In fact, thereby it is..

**Comment by shuhab** [comment]
I am experiencing the same issue as the others

**Comment by Haehnchen** [comment]
fixed in 0.8

**Comment by Francismori7** [comment]
Finally! Thanks!

**Comment by EvgeniyN** [comment]
Hi,
Fix what U provide expects \\App namespace as default project namespace, but frequently devs change it to real project name like \\MyBlog, \\CoolShop etc. and it still doesn't work.

Maybe U can provide settings for this feature in Settings dialog.
Tnx.
